[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
data_dir = /var/lib/odoo
admin_passwd = admin_master_password_123
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo_password
db_name = coffee_shop_v0_20260318_134912
list_db = True
proxy_mode = False
workers = 0
limit_memory_hard = 2684354560
limit_memory_soft = 2147483648
limit_time_cpu = 600
limit_time_real = 1200